---

- name: Install pip
  apt:
    pkg: 
      - python3-pip
  become: true

- name: Install jupyter
  shell: pip3 install jupyter s3contents && mkdir -p /home/{{ vm_user }}/.jupyter/
  become: true
