---

- name: Install pip
  apt:
    pkg: 
      - python3-pip
  become: true

- name: Install jupyter
  shell: pip install --user jupyter s3contents && mkdir -p /home/cloudadm/.jupyter/
  become: true
  become_user: "{{ vm_user }}"
