---

- name: Install pip
  apt:
    pkg: 
      - python3-pip
      - s3fs
  become: true

- name: Install jupyter
  shell: pip3 install --user jupyter s3contents
  become: true
  become_user: "{{ vm_user }}" 