---
- name: Include "{{ansible_os_family}}" JupyterVM recipe
  include: "{{ansible_os_family}}.yaml"
  static: false

- name: create need dirs
  shell: mkdir -p /home/{{ vm_user }}/.jupyter
  become: true
  become_user: "{{ vm_user }}"

- name: Configure s3 for jupyter
  template:
    src: jupyter_notebook_config.py
    dest: /home/{{ vm_user }}/.jupyter/jupyter_notebook_config.py
    owner: "{{ vm_user }}"
  become: true
  become_user: "{{ vm_user }}" 
  when: persistence == "s3"

- name: Launch jupyter notebook
  shell: nohup jupyter notebook --ip 0.0.0.0 --port {{ jupyter_port }}> $HOME/log_jupyter.txt &
  become: true
  become_user: "{{ vm_user }}"
