- name: install rclone
  shell: curl https://rclone.org/install.sh | bash
  ignore_errors: yes

- name: Create conf dir for rclone
  file:
    path: $HOME/.config/rclone
    state: directory
    recurse: yes
    owner: "{{ vm_user }}"
    group: "{{ vm_user }}"
  become: true
  become_user: "{{ vm_user }}"

- name: Create cache dir for rclone
  file:
    path: /tmp/cache
    state: directory
    recurse: yes
    owner: "{{ vm_user }}"
    group: "{{ vm_user }}"
  become: true
  become_user: "{{ vm_user }}"

- name: config rclone
  template:
    src: rclone.conf
    dest: $HOME/.config/rclone/rclone.conf
    owner: "{{ vm_user }}"
  become: true
  become_user: "{{ vm_user }}"
  
- name: mount notebooks vFS
  shell: "rclone mount --config $HOME/.config/rclone/rclone.conf --daemon --cache-dir /tmp/cache --vfs-cache-mode full s3:{{ s3_bucket }} $HOME/notebooks"
  become: true
  become_user: "{{ vm_user }}"
